[build]
  publish = "dist"
  command = "npm run generate"
  functions = "functions"
[build.environment]
  NODE_VERSION = "14.15"
[functions."change"]
schedule = "0 0 1 */6 *"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"